const cdata = [{
  avatarUrl: '/static/images/avatars/avatar_3.png',
  EmpId: '001',
  Name: 'Hi',
  JobTitle: 'aaa',
  Dept: 'a',
  Phone: '0000000000',
  ZipCode: '00000',
  City: 'fda',
  Address: 'aaaaaa',
  MonthSalary: '100000',
  AnnualLeave: '10',
},
{
  avatarUrl: '/static/images/avatars/avatar_4.png',
  EmpId: '002',
  Name: 'He',
  JobTitle: 'bbb',
  Dept: 'b',
  Phone: '111111111',
  ZipCode: '11111',
  City: 'bbb',
  Address: 'bbbbbb',
  MonthSalary: '200000',
  AnnualLeave: '5',
}];
export default cdata;
